FROM bitnami/node:12 as builder
ENV NODE_ENV="production"
RUN install_packages libudev-dev libusb-1.0-0-dev build-essential python3 make g++ gcc
COPY . /opt/monitor/ 
WORKDIR /opt/monitor
RUN yarn && yarn build && yarn install --production

FROM bitnami/node:12-prod
ENV NODE_ENV="production"
COPY --from=builder /opt/monitor/build /opt/monitor/package.json /opt/monitor/node_modules /opt/monitor/wrapper.sh /opt/monitor/
WORKDIR /opt/monitor
ENTRYPOINT exec /opt/monitor/wrapper.sh

